### PR TITLE
add support for change startAngle

### PR DESCRIPTION
**Pull request by hildert**
This library works really cool and saved my time,thanks for you work :).
I am using it in my project. But I found the start angle can't be changed. so I made the change to the start angle.
Please review the code. Hopefully it could be helpful.

### CODE REVIEW

**Comment by Eclair** [comment]
Hi @hildert, thank you! I was planning to made it in future, and that's why I defined and used "StartAngle" constant in all calculations. I've tested your changes and it looks cool, all works like a charm! Can you please only replace property usage from self.startAngle to _startAngle inside the class? Just to keep it strict, so there will be no mistakes with place where are you using it.

After that I'll make an v0.11 and update cocoa pods.

Thanks

**Comment by hildert** [comment]
Hi @Eclair,thanks for you review :). I have changed all self.startAngle to _startAngle, and I have tested it. Thanks

**Comment by Eclair** [comment]
@hildert Thank you for your contribution. I pushed new version (0.11) to the cocoapods, and it will be available soon! http://cocoapods.org/pods/CircleProgressBar

**Comment by hildert** [comment]
@Eclair You are welcome! It's my first time send a pull request. I learnd so much from your code and code style. Thank you again : )

**Pull request merged**
